#!/usr/bin/env python3
"""
OptimusDB Development Docker Compose Generator
Generates docker-compose.dev.yml with combined containers
"""

import argparse
import sys

HEADER = """version: '3.8'

# OptimusDB Development Deployment - Auto-generated
# Architecture: Single Container (OptimusDB + TinyLlama)
# Total Containers: {num_agents}
# Generated by: scripts/generate-dev-compose.py

services:
"""

DEV_AGENT_TEMPLATE = """
  optimusdb-agent-{agent_id}:
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: optimusdb-dev-agent-{agent_id}
    hostname: optimusdb-dev-agent-{agent_id}
    restart: unless-stopped
    ports:
      - "{rest_port}:9091"
      - "{creds_port}:8081"
    environment:
      - AGENT_ID={agent_id}
      - AGENT_PORT=9091
      - CREDENTIALS_PORT=8081
      - IPFS_API=/ip4/127.0.0.1/tcp/5001
      - ORBITDB_DIRECTORY=/data/orbitdb
      - SQLITE_PATH=/data/optimusdb.db
      - BOOTSTRAP_PEERS={bootstrap_peers}
      - ELECTION_ENABLED=true
      - TINYLLAMA_ENDPOINT=http://127.0.0.1:8080/v1/completions
      - TINYLLAMA_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - agent{agent_id}-dev-data:/data
    networks:
      - optimusdb-dev-network
"""

NETWORK_SECTION = """
networks:
  optimusdb-dev-network:
    driver: bridge
"""

VOLUMES_HEADER = """
volumes:
"""

VOLUME_TEMPLATE = """  agent{agent_id}-dev-data:
"""


def generate_dev_compose(num_agents: int = 8) -> str:
    """Generate development docker-compose.yml content"""

    output = []

    # Header
    output.append(HEADER.format(num_agents=num_agents))

    # Agents
    for agent_id in range(1, num_agents + 1):
        rest_port = 9090 + agent_id
        creds_port = 8080 + agent_id

        # Bootstrap peers (all previous agents)
        peers = []
        for i in range(1, agent_id):
            peers.append(f"/ip4/optimusdb-dev-agent-{i}/tcp/9091")
        bootstrap_peers = ",".join(peers) if peers else ""

        output.append(DEV_AGENT_TEMPLATE.format(
            agent_id=agent_id,
            rest_port=rest_port,
            creds_port=creds_port,
            bootstrap_peers=bootstrap_peers
        ))

    # Network
    output.append(NETWORK_SECTION)

    # Volumes
    output.append(VOLUMES_HEADER)
    for agent_id in range(1, num_agents + 1):
        output.append(VOLUME_TEMPLATE.format(agent_id=agent_id))

    return "".join(output)


def main():
    parser = argparse.ArgumentParser(
        description="Generate OptimusDB development docker-compose.yml"
    )
    parser.add_argument(
        "--agents",
        type=int,
        default=8,
        help="Number of agents (default: 8)"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="docker-compose.dev.yml",
        help="Output file (default: docker-compose.dev.yml)"
    )

    args = parser.parse_args()

    if args.agents < 1:
        print("Error: Number of agents must be at least 1", file=sys.stderr)
        sys.exit(1)

    content = generate_dev_compose(num_agents=args.agents)

    with open(args.output, 'w') as f:
        f.write(content)

    print(f"✅ Generated {args.output}")
    print(f"   - {args.agents} combined containers")
    print(f"   - Each: OptimusDB + TinyLlama")
    print(f"   - Est RAM: ~{args.agents * 3}GB")


if __name__ == "__main__":
    main()